dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_0?characterEncoding=utf-8
    username: mysql
    password: mysql
  ds_1:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_1?characterEncoding=utf-8
    username: mysql
    password: mysql
rules:
  - !SHARDING
    autoTables:
      t_user:
        actualDataSources: ds_$->{0..1}
        shardingStrategy:
          standard:
            shardingColumn: addr_id
            shardingAlgorithmName: t_user_volume_range
        keyGenerateStrategy:
          column: user_id # 注意插入语句中不能包含该列，否则不会自动生成id
          keyGeneratorName: snowflake_gen
    shardingAlgorithms:
      t_user_volume_range:
        type: VOLUME_RANGE # 通过props参数就可以估算出需要多少张分片表，用户创建逻辑表t_user时shardingsphere会自动创建各个分片表
        props:
          range-lower: 2  # 范围下界，分片键值小于 range-lower 的所有记录单独存入一张分片表，通常是t_user_0
          range-upper: 30 # 范围上界，分片键值大于等于 range-upper 的所有记录单独存入一张分片表
          sharding-volume: 10 # 在[range-lower, range-upper)范围的内的所有记录按照每张分片表最多有sharding-volume条记录进行分片。
    keyGenerators:
      snowflake_gen:
        type: SNOWFLAKE

#打印sql
props:
  sql-show: true