dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_0?characterEncoding=utf-8
    username: mysql
    password: mysql
  ds_1:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_1?characterEncoding=utf-8
    username: mysql
    password: mysql
rules:
  - !SHARDING
    autoTables:
      t_user:
        actualDataSources: ds_$->{0..1}
        shardingStrategy:
          standard:
            shardingColumn: addr_id
            shardingAlgorithmName: t_user_boundary_range
        keyGenerateStrategy:
          column: user_id # 注意插入语句中不能包含该列，否则不会自动生成id
          keyGeneratorName: snowflake_gen
    shardingAlgorithms:
      t_user_boundary_range:
        type: BOUNDARY_RANGE # 通过props参数就可以估算出需要多少张分片表，用户创建逻辑表t_user时shardingsphere会自动创建各个分片表
        props:
          sharding-ranges: 10,20,25,40  # 多个范围边界以逗号间隔，比如5个范围[0,10), [10,20), [20,25), [25,40), [40,inf]
    keyGenerators:
      snowflake_gen:
        type: SNOWFLAKE

#打印sql
props:
  sql-show: true