dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_0?characterEncoding=utf-8
    username: mysql
    password: mysql
  ds_1:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_1?characterEncoding=utf-8
    username: mysql
    password: mysql
rules:
  - !SHARDING
    autoTables:
      t_user:
        actualDataSources: ds_$->{0..1}
        shardingStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: t_user_auto_interval
        keyGenerateStrategy:
          column: user_id # 注意插入语句中不能包含该列，否则不会自动生成id
          keyGeneratorName: snowflake_gen
    shardingAlgorithms:
      t_user_auto_interval:
        type: AUTO_INTERVAL # 通过props参数就可以估算出需要多少张分片表，用户创建逻辑表t_user时shardingsphere会自动创建各个分片表
        props:
          datetime-lower: '2023-01-01 00:00:00'  # 时间下界，分片键值小于 datetime-lower 的所有记录单独存入一张分片表，通常是t_user_0
          datetime-upper: '2026-01-01 00:00:00' # 时间上界，分片键值大于等于 datetime-upper 的所有记录单独存入一张分片表
          sharding-seconds: 31536000 # 在[datetime-lower, datetime-upper)时间范围的内的所有记录按照每张分片表最多承载sharding-seconds秒进行分片。
    keyGenerators:
      snowflake_gen:
        type: SNOWFLAKE

#打印sql
props:
  sql-show: true