dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_0?characterEncoding=utf-8
    username: mysql
    password: mysql
  ds_1:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_1?characterEncoding=utf-8
    username: mysql
    password: mysql

rules:
  - !SHARDING
    # 数据分片规则配置：根据id分表
    tables:
      t_user:
        actualDataNodes: ds_$->{0..1}.t_user_$->{0..2}
        databaseStrategy:
          complex:
            shardingColumns: user_id, addr_id
            shardingAlgorithmName: t_user_database_complex_inline

        tableStrategy:
          complex:
            shardingColumns: user_id, addr_id
            shardingAlgorithmName: t_user_table_complex_inline

    # 分片算法配置
    shardingAlgorithms:
      t_user_database_complex_inline:
        type: COMPLEX_INLINE
        props:
          sharding-columns: user_id, addr_id
          algorithm-expression: ds_$->{(user_id + addr_id) % 2}
      t_user_table_complex_inline:
        type: COMPLEX_INLINE
        props:
          sharding-columns: user_id, addr_id
          algorithm-expression: t_user_$->{(user_id + addr_id) % 3}

#打印sql
props:
  sql-show: true