dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_0?characterEncoding=utf-8
    username: mysql
    password: mysql
  ds_1:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid必须用url，而不是jdbcUrl
    url: jdbc:mysql://127.0.0.1:3306/ds_1?characterEncoding=utf-8
    username: mysql
    password: mysql

rules:
  - !SHARDING
    tables:
      t_user:
        actualDataNodes: ds_$->{0..1}.t_user_$->{202401..202406}
        databaseStrategy:
          standard:
            shardingColumn: age
            shardingAlgorithmName: database_inline
        tableStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: t_user_table_interval

    # 分片算法配置
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_$->{age % 2}
      t_user_table_interval:
        type: INTERVAL
        props:
          datetime-pattern: "yyyy-MM-dd HH:mm:ss"  #分片字段格式
          datetime-lower: "2024-01-01 00:00:00"
          datetime-upper: "2024-06-30 23:59:59"
          sharding-suffix-pattern: "yyyyMM"  #分片名后缀，可以是MM，yyyyMMdd等。
          datetime-interval-amount: 1  #分片键时间间隔，超过该时间间隔将进入下一分片，这里是一个月
          datetime-interval-unit: "MONTHS"  # Java ChronoUnit 的枚举值

#打印sql
props:
  sql-show: true